### ISSUE TITLE
Integration ionic material in ionic project

### ISSUE THREAD

**Issue by gauravsaini03** [zachsoft/Ionic-Material#11] opened 2015-03-28 07:42 UTC
@zachsoft Can you please let me know about how to use ionic material. I have install it using bower and now I saw directories in my lib folder. Also, included the ionic-material.js and css files inindex.html
But still did not see the button or any other components changed in material design.

Can you please please help integrating or any small doc how to include it ? I know api doc is on the way, but again a smal 5-10 lines of itegration will help :) 
So, after that we can also contribute to the doc.

**Comment by emanb29** [comment] 2015-03-29 08:41
+1. I can't figure out for the life of me how to actually use this framework, nor if I'm even installing it right (per #10)

**Comment by Alexintosh** [comment] 2015-03-29 11:42
+1

**Comment by maaaikoool** [comment] 2015-03-29 11:44
+1

**Comment by michaelbina** [comment] 2015-03-29 16:23
Hey guys,

The best way to figure out how to use the library before the API docs are released is to inspect the "preview" phone on http://ionicmaterial.com/.  The pages are injected with an iFrame, so you can easily see the entire source for the page.

You are not supposed to use the ion-* tags for the most part and basically just need to add the class "ionic" to your main view and then use standard ionic classes without the ion-* tags.  

Here is an example of a working header bar:

  <div class="bar bar-header bar-positive">
    <button class="button button-icon icon ion-navicon flat" menu-toggle="left" ng-hide="$exposeAside.active"></button>
    <h1 class="title fab-left">Spaces</h1>
    <button class="button button-icon icon ion-plus-round flat pull-right" ng-click="spacesController.showNewSpaceModal()"></button>
  </div>

And an example of a working category list:

      <div class="list condensed-space no-padding animate-blinds done done done done">
          <div class="card dark-bg in" style="-webkit-transition: 0.13s; transition: 0.13s;" ng-repeat="space in spacesController.spaces" item="space" ui-sref="app.tabs.space({spaceId: space.id})">
              <a class="item clear-bg item-bg-image waves-effect waves-button waves-light has-mask-reverse">
                  <h2>{{space.attributes.name}}</h2>
                  <img src="{{space.attributes.profilePhotoUrl}}" style="-webkit-transition: 0.06s; transition: 0.06s;">
              </a>
          </div>
      </div>


Also, in case you didn't see it, this message was just added to the README:

*With the big increase of interest in this project, I can confirm there will be a major update to this project soon. Please hang tight while we finish writing the directives, API, and complete testing. The goal is for the first version (alpha) to be released in April. With some help, we can speed it along.*

Seems like @zachsoft is not paying attention to the forums so it's best to probably try and just figure stuff out on your own until the API docs are released.  I'm happy to help until then though.

**Comment by zachsoft** [comment] 2015-03-30 18:15
@michaelbina and others, thanks for helping out up to this point, you guys rock.

Things have been crazy here with some changes on the personal side of things. Things are looking back to normal, so I should be able to help support better. I can help with existing issues, but honestly, what I'm releasing this week should resolve 99% of the struggle.

You've all been super patient awaiting the alpha release and better documentation - I just wanted to pop in and let you guys know where I'm at: the code for the alpha release version was completed a couple days ago - main things have been refactoring to make an API that's ease to use and consistency, and resolving the outstanding issues. It's taken longer than I'd have liked, but I feel like the extra effort is worth it for ease of use/consistency.

The big request items had a lot of emphasis: uI-router support, ionic 1.0 compat, and animation control. A demo app that contains the "kitchen sink" with all the available features is almost done, which is the final piece I'm working on before I commit. After that, I aim to lay down a wiki with info, coding standards and my vision for the project so whoever wants to can more easily help out.

Thanks for all the feedback and interest. When alpha's released and you guys run through it, let me know of the pain points and where you guys want to see improvements.

**Comment by rmclain** [comment] 2015-04-01 03:56
Here's to hoping this helps some others get this running in the emulator easier.  From a 
>ionic start myApp blank

Then run  
>bower install ionic-material 

This does have some compatibility issues, but you should be fine selecting the newest versions of each.  Then I moved the www/lib/ionic-material/preview/img/* to www/img/preview/* 

The final index.html looks like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="lib/ionic-material/dist/material-ionic.min.css" rel="stylesheet">
    <link href="lib/ionic-material/preview/css/device.css" rel="stylesheet">
    <link href="lib/ionic-material/preview/css/preview.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <!-- IF using Sass (run gulp sass first), then uncomment below and remove the CSS includes above
    <link href="css/ionic.app.css" rel="stylesheet">
    -->

    <!-- ionic/angularjs js -->
    <script src="lib/ionic/js/ionic.bundle.js"></script>

    <!-- cordova script (this will be a 404 during development) -->
    <script src="cordova.js"></script>

    <!-- your app's js -->
    <script src="js/app.js"></script>
  </head>
  <body ng-app="starter">
    <div class="ionic">
        <div class="bar bar-header bar-positive">
            <button class="button button-icon icon ion-navicon flat"></button>
            <button class="button button-icon icon ion-android-more-vertical flat pull-right"></button>
            <h1 class="title fab-left">Categories</h1>
        </div>
        <div class="content has-header">
            <div class="list condensed-space no-padding animate-blinds">
                <div class="card dark-bg">
                    <a class="item clear-bg item-bg-image waves-effect waves-button waves-light has-mask-reverse" >
                        <h2>Toronto</h2>
                        <p>Drake's Raptastic Raptors</p>
                        <img src="img/preview/toronto.jpg">
                    </a>
                </div>
                <div class="card energized-bg">
                    <a class="item clear-bg item-bg-image waves-effect waves-button waves-light has-mask-reverse" >
                        <h2>Scotland</h2>
                        <p>Land of Unicorns</p>
                        <img src="img/preview/scotland.jpg">
                    </a>
                </div>
                <div class="card assertive-bg">
                    <a class="item clear-bg item-bg-image waves-effect waves-button waves-light has-mask-reverse" >
                        <h2>Kyoto</h2>
                        <p>Cultural Experience</p>
                        <img src="img/preview/kyoto.jpg">
                    </a>
                </div>
                <div class="card balanced-bg">
                    <a class="item clear-bg item-bg-image waves-effect waves-button waves-light has-mask-reverse" >
                        <h2>New Zealand</h2>
                        <p>More Than the Other Down Under</p>
                        <img src="img/preview/new-zealand.jpg">
                    </a>
                </div>
                <div class="card royal-bg">
                    <a class="item clear-bg item-bg-image waves-effect waves-button waves-light has-mask-reverse" >
                        <h2>Hawai'i</h2>
                        <p>Paradise Getaway</p>
                        <img src="img/preview/hawaii.jpg">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script src="lib/Waves/dist/waves.min.js"></script>
    <script src="lib/ionic-material/dist/material-ionic.min.js"></script>
    <script>
    Waves.displayEffect();
    setTimeout(function() {
        Mi.motion.blindsDown({
            selector: '.card'
        });
    }, 500);
    </script>
</body>
</html>
```

**Comment by panospcm** [comment] 2015-04-13 13:23
Hello fellow developers! Do we have a possible timetable on when the next version of this awesome library will be released ?

Thanks!

**Comment by kurniawandi** [comment] 2015-04-17 06:56
how is the result? is it like this?
![likethis](https://cloud.githubusercontent.com/assets/11989955/7197302/80c2773e-e509-11e4-863a-c3b658189de4.jpg)

**Comment by nick2474** [comment] 2015-04-27 19:24
Hi i was trying to integrate to the ionic project tab  the ionic material with the following command but is showing an error, any help will be appreciated:

~/Sites/ionicApps/test/tab$ bower install ionic-material
bower not-cached    git://github.com/zachsoft/Ionic-Material.git#*
bower resolve       git://github.com/zachsoft/Ionic-Material.git#*
bower not-cached    git://github.com/driftyco/ionic-bower.git#1.0.0-rc.4
bower resolve       git://github.com/driftyco/ionic-bower.git#1.0.0-rc.4
bower ENOTDIR       ENOTDIR, mkdir '/var/folders/lv/051390rx2q5dtfjxbk4dwd040000gn/T/user/bower'

Stack trace:
Error: ENOTDIR, mkdir '/var/folders/lv/051390rx2q5dtfjxbk4dwd040000gn/T/didierh/bower'

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:830:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:856:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:774:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:590:44
System info:
Bower version: 1.4.1
Node version: 0.10.33
OS: Darwin 13.4.0 x64

**Comment by sharky101** [comment] 2015-05-05 16:13
@zachsoft are there any plans to port the css in this project to sass?

**Comment by raibutera** [comment] 2015-05-15 00:15
@sharky101 I did so last night. Please check out release 0.1.x

**Closed** 2015-05-18 18:40 UTC

**Comment by alok12** [comment] 2015-05-20 09:50
I have download it and run on our server it is given error " Error: [$injector:unpr] Unknown provider: ionicMaterialInkProvider <- ionicMaterialInk <- LoginCtrl
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=ionicMaterialInkProvider%20%3C-NaNonicMaterialInk%20 " and also ionicMaterialMotion in error.

**Comment by raibutera** [comment] 2015-05-20 10:04
Did you inject ionic-material into your module

**Comment by alok12** [comment] 2015-05-20 10:17
I have added it as angular.module('starter', ['ionic', 'ionic-material']) but it is also given error 

my index file code is 
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic' rel='stylesheet' type='text/css'>
    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="lib/ionic-material/ionic.material.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="lib/ionic-material/ionic.material.min.js"></script>
    
    <script src="cordova.js"></script>
    
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>
</head>
<body ng-app="starter">
    <ion-nav-view></ion-nav-view>
</body>
</html>

Error is => Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic-material due to:
Error: [$injector:nomod] Module 'ionic-material' is not available!

**Comment by raibutera** [comment] 2015-05-20 10:18
Can you please create a plunkr/codepen

**Comment by alok12** [comment] 2015-05-20 10:22
Can i mail you index file? or you can guide me i have included the ionic.material.min.js and also the ionic.material.min.css .
I have run this downloaded code but not working. May be i have not create any service ionicMaterialInk.

**Comment by raibutera** [comment] 2015-05-20 10:24
You don't need to create `ionicMaterialInk`

Please create a [codepen](http://codepen.io/pen/). Unfortunately I don't have the time or resources to try and build your project from scratch.

**Comment by alok12** [comment] 2015-05-20 10:28
Thanks i am trying

**Comment by alok12** [comment] 2015-05-20 11:05
How to inject ionic-material?

**Comment by alok12** [comment] 2015-05-20 11:29
Hello Please check the basic code on codepen and check the screen shot attached.

Thanks For help.
![screenshot from 2015-05-20 16 51 32](https://cloud.githubusercontent.com/assets/8359487/7724704/9695eace-ff11-11e4-8b07-2616c7933c4b.png)

**Comment by alok12** [comment] 2015-05-20 11:30
http://codepen.io/anon/pen/rVMaeN

**Comment by raibutera** [comment] 2015-05-20 12:29
I can see your problem, you're using an old version of Ionic Material. Try
0.4.x

**Comment by heradonbenin** [comment] 2015-05-24 04:31
please @raibutera  @zachsoft  i'm facing with the same error with @alok12 , i get ionic material 0.4.2 but i get the below error . can't explore demo application.

Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic-material due to:
Error: [$injector:nomod] Module 'ionic-material' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by zdenal** [comment] 2015-05-30 14:17
I have the same issue as @heradonbenin with 0.4.2 version.

**Comment by bowenliang123** [comment] 2015-05-30 22:32
+1

**Comment by jlebras** [comment] 2015-05-31 00:53
Yep I had the same problem, I think I got it guys !
I just replaced the file "ionic.material.min.js" in the demo/www/lib/ionic-material folder by the one from the dist folder and it seems to work, no more dependencies errors.

The demo folder is not up to date with the last version of ionic material I guess...

**Comment by raibutera** [comment] 2015-06-01 01:41
yup @jlebras it's not up to date

**Comment by zdenal** [comment] 2015-06-01 07:56
Hi @jlebras, thanks for feedback. I am using version via bower install. I was trying install latest version even install from master - I got the same issue as @heradonbenin

**Comment by ityao** [comment] 2015-06-05 13:07
save problem to run the demo!

**Comment by ityao** [comment] 2015-06-05 13:08
same problem when running the demo!

**Comment by uttesh** [comment] 2015-06-10 16:32
i had the same issue, solved by referring the "ionic.material.js" present in the "dist" folder,which as "ionicMaterialInk", "ionicMaterialMotion" providers. this providers are missing in the parent demo folder "ionic.material.min.js" folder.

changes made to solve the provider issue :

index.html :

app.js :

angular.module('starter', ['ionic', 'starter.controllers','ionMdInput','ionic-material'])

hope this will help.

**Comment by delalis** [comment] 2015-06-10 17:36
@uttesh I'm having the same Provider issue.  Could you please be more specific in describing your solution?

Do you mean that you changed line 8 of app.js from:
angular.module('starter', ['ionic', 'starter.controllers', 'ionMdInput'])
to
angular.module('starter', ['ionic', 'starter.controllers','ionMdInput','ionic-material'])

???

And what did you do in index.html?  My index.html I got from the demo app does not currently have an angular.module(...) function call...do you mean to say that we add this function call in index.html somewhere?  if so, where?

More details please...

**Comment by uttesh** [comment] 2015-06-10 17:46
@delalis  yes app.js i changed the line 8 as u mentioned and in index.html change the src location of the "ionic.material.min.js" file present under the "dist" folder i.e under "www\lib\ionic-material\dist"

**Comment by delalis** [comment] 2015-06-10 19:03
Okay.  Got it working.  Thanks!

**Comment by niwasmala** [comment] 2015-06-20 05:36
Hi guys, I also experienced same problem. 
At first I start with copying demo project, I think the demo project has older version of ionic-material (and perhaps other libs). Then I read how to install using bower. After I install using bower, somehow it create bower_components folder in my project folder, then I copy bower_components/ionic-material/dist/ into www/lib/ionic-material, and it works!

Currently I manually copy from bower_components/ to www/lib/. Or is there a way when we install using bower, it will go directly to www/lib folder?

**Comment by uttesh** [comment] 2015-06-20 08:50
@niwasmala  provide the directory location in .bowerrc file, bower will directly install the components to provided location .

sample : .bowerrc

{
  "directory": "www/lib"
}

**Comment by niwasmala** [comment] 2015-06-20 10:20
Alright, thanks!

**Comment by tpalmer75** [comment] 2015-06-24 19:22
I have installed Ionic-Material via bower and referenced to the "dist" files, but I am still receiving this error:

Uncaught Error: ionic-material could not load angular module :(

![image](https://cloud.githubusercontent.com/assets/5341422/8339350/023ea5e0-1a74-11e5-94bf-ff00e49221f8.png)

![image](https://cloud.githubusercontent.com/assets/5341422/8339358/0e198d9e-1a74-11e5-8d73-3a21d924c7f1.png)

It still seems that I have the wrong version of angular/ionic, but I'm using the latest versions of all of the dependencies. Any thoughts?

**Comment by codingL3gend** [comment] 2015-06-25 01:31
You should reference ionic material after ionic itself

**Comment by tpalmer75** [comment] 2015-06-25 14:32
@codingL3gend That was it. Thanks!

**Comment by codingL3gend** [comment] 2015-06-25 21:37
@tpalmer75 no problem

**Comment by moeenuddin** [comment] 2015-07-07 06:37
@jlebras Thanks. replacing js file worked!

**Comment by MoPHL** [comment] 2015-09-11 17:34
After running bower install ionic-material I get the message "bower ECONFLICT Unable to find suitable version for ionic" and nothing is installed. I tried manually copying the files from the github repository, but I'm still getting "Error: [$injector:nomod] Module 'ionic-material' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."
I've also tried all the things mentioned above in this thread, but nothing worked.
I have a simple ionic start ProjectName blank project into which I copied the demo from the github.
Any thoughts?

**Comment by tamalesimon** [comment] 2015-10-26 17:14
with the example above how would one make the categories to scroll... any ideas

**Comment by rig1** [comment] 2015-11-19 07:04
I have got a problem when i loading one of my html it shows   "Uncaught TypeError: Cannot read property 'className' of undefined, http://localhost:8100/lib/ionic-material/dist/ionic.material.min.js, Line: 13"
 even i had added this js file in my index.html

**Comment by MichelleDiamond** [comment] 2016-01-20 16:52
Could somebody please advise. I am using a background image in <ion-content> consequently card-item doesnt show. I have no idea how to work around this.
Much appreciated.
